
name: av_comparatives

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    name: AV deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    - name: Deployment
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER }}
        key: ${{ secrets.KEY }}
        username: ${{ secrets.USER }}

        script: |
          cd /var/www/av-comparatives/av-comparatives
          git fetch origin development
          git reset --hard origin/development
          npm install
          pm2 restart 0
